# Токен бота (получить у @BotFather)
# Задайте переменную окружения BOT_TOKEN
# Токен бота. Задайте BOT_TOKEN или укажите здесь (для production используйте env)
bot.token=${BOT_TOKEN:7334989424:AAF-LBA30Y-3xowV1k5ZthTHIFlD4EHifkw}

# Файл для сохранения данных парка
bus.storage.file=buspark.dat
